[package]
name = "poyin-trading"
version = "1.0.0"
description = "Ponyin Trading Intel"

[[module]]
name = "web"
source = "wasmer/static-web-server:1"

[fs]
public = "dist"

[[command]]
name = "web"
module = "web"
runner = "wasi"

[command.annotations.wasi]
main-args = ["--port", "8080", "--root", "/public"]